config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do 
    member do
      post 'vote' #/posts/3/vote. It is put pertaining to individual routes
    end

# collection do
# post 'archive' #/posts/archive. Not pertaining to individual routes
# end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :user
  belongs_to :post #no need to specify the foreign key here as the asumptions are correct.

  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by slug: params[:post_id]
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    #this will associate this comment.post foreign key to this post id. Mass assign the permiteed attribute.
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Your comment was added."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on one post once."
        end
        redirect_to :back
      end
      format.js
    end
  end

end

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class= 'row'>
  <div class='span0 well text-center'>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
    <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
    <span id="comment_<%=comment.id %>_votes"> <%= comment.total_votes %> votes </span> <!-- span and id needed to identify and tag this portion to be parsed to js -->
    <br/>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
    <i class='icon-arrow-down'></i>
    <% end %>
  </div>

  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
    on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
      <span class='quiet'>by</span> <%= link_to comment.user.username, user_path(comment.user) %>
      <small>at <%= display_datetime(comment.created_at) %></small>
  </div>

</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes")
<% else %>
  alert('You can only vote on a comment once.');
<% end %>