config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do 
    member do
      post 'vote' #/posts/3/vote. It is put pertaining to individual routes
    end

# collection do
# post 'archive' #/posts/archive. Not pertaining to individual routes
# end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :user
  #normally, we do not need to be explicit, but because we are using "creator" instead of user, we have to be explicit to state:
  #the foreign_key and also the class name.
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories  

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  sluggable_column :title

end

app/controllers/posts_controller.rb
 class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator, only: [:edit, :update]


  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse #start an instance variable.
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params) #creating private methods to handle strong params
    @post.user = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update    
    if @post.update(post_params)
      flash[:notice] = "This post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do 
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on one post once."
        end
        redirect_to :back      
      end
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
    #strong params through require that only permits the following actions above.
    #use binding pry to check the submission details.
  end

  def set_post
    @post = Post.find_by slug: params[:id]    
  end

  def require_creator
    access_denied unless logged_in? and (logged_in? and current_user == @post.user || current_user.admin?)

  end
end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class='well'>
 <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group'>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
        <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
    </div>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary')%> 
    <!-- new record is an instance record method from active record object to tell us is this new, has it been saved?-->
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
    <div class='span0 well text-center'>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
        <span id='post_<%=post.slug%>_votes'><%= post.total_votes %> votes </span>
      <br/>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %> <!--  there is a javascript that comes from rails that is  turning this link to a form through "method: 'post' -->
        <i class='icon-arrow-down'></i>
      <% end %>
    </div>
    <div class='span8 well'>
      <%= render post.categories %>
      <h4><%= link_to post.title, fix_url(post.url) %></h4>
      <p><%= post.description %></p>
      <p>
        <span class='quiet'>posted by</span> <%= link_to post.user.username, user_path(post.user) %> 
        <!-- username to be resolved -->
        <small>at <%= display_datetime(post.created_at) %></small>
      </p>
      <small>
        <span>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </span>
      </small>
    </div>
  </div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>
<%= render 'form' %> <!-- if we do not put 'shared_form', if will look for a partial called 'form' in the same folder. -->

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class="pull-right">
    [<%= link_to 'edit this post', edit_post_path(@post)%>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
  <hr/>
</p>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>
    <div class='control-group'>
      <%= f.label :body, 'Leave a comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
      <%= f.submit "Create comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<h5> Comments:</h5>

<% @post.reload.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes")
<% else %>
  alert('You can only vote on a post once.');
<% end %>